# Project
version=2.3.0
group=tschipp.carryon

# Common
minecraft_version=1.21.4
mod_name=Carry On
mod_author=Tschipp, PurpliciousCow
mod_id=carryon
license=GNU LGPLv3
credits=
description=Carry On is a simple mod that improves game interaction by allowing players to pick up, carry, and place single block Tile Entities using only their empty hands.
minecraft_version_range=[1.21.4, 1.22)
# Forge
forge_version=54.0.12
forge_loader_version_range=[54,)
forge_version_range=[54,)
parchment_mappings=2024.12.29-1.21.4
//forge_ats_enabled=true

# Fabric
fabric_version=0.113.0+1.21.4
fabric_loader_version=0.16.9
parchment_mappings_fabric=1.21.4:2024.12.29

# Neoforge
neoforge_version=21.4.109-beta
neoforge_loader_version_range=[4,)
neogradle.subsystems.parchment.minecraftVersion=1.21.4
neogradle.subsystems.parchment.mappingsVersion=2024.12.29


# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mixinextras_version=0.3.6
cloth_config_version=17.0.144