# Project
version=2.2.4
group=tschipp.carryon

# Common
minecraft_version=1.21.1
mod_name=Carry On
mod_author=Tschipp, PurpliciousCow
mod_id=carryon
license=GNU LGPLv3
credits=
description=Carry On is a simple mod that improves game interaction by allowing players to pick up, carry, and place single block Tile Entities using only their empty hands.
minecraft_version_range=[1.21.1, 1.21.2)
# Forge
forge_version=52.1.14
forge_loader_version_range=[52,)
forge_version_range=[52,)
parchment_mappings=2024.11.17-1.21.1
//forge_ats_enabled=true

# Fabric
fabric_version=0.116.8+1.21.1
fabric_loader_version=0.18.4
parchment_mappings_fabric=1.21.1:2024.11.17

# Neoforge
neoforge_version=21.1.230
neoforge_loader_version_range=[4,)
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17


# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mixinextras_version=0.3.6