# Project
version=2.11.0
group=tschipp.carryon

# Common
minecraft_version=26.2
mod_name=Carry On
mod_author=Tschipp, PurpliciousCow
mod_id=carryon
license=GNU LGPLv3
credits=
description=Carry On is a simple mod that improves game interaction by allowing players to pick up, carry, and place single block Tile Entities using only their empty hands.
minecraft_version_range=[26.2, 27)
minecraft_version_range_fabric=>=26.2 <27
neo_form_version=26.2-1
java_version=25
mod_dev_version=2.0.141

# Fabric
fabric_version=0.156.0+26.2
fabric_loader_version=0.19.3
loom_version=1.17-SNAPSHOT
modmenu_version=18.0.0

# Neoforge
neoforge_version=26.2.0.41-beta
neoforge_loader_version_range=[4,)

# Forge
forge_version=65.1.0
forge_loader_version_range=[65,)
net.minecraftforge.gradle.merge-source-sets=true

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mixinextras_version=0.5.4
cloth_config_version=26.2.155
