plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle' version '[7.0.17,8)'
    id 'net.minecraftforge.jarjar' version '0.2.3'
    id 'idea'
}

base {
    archivesName = "${mod_id}-forge-${minecraft_version}"
}

/*
mixin {
    add sourceSets.main, "${mod_id}.refmap.json"

    config "${mod_id}.mixins.json"
    config "${mod_id}.forge.mixins.json"
}*/

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                "MixinConfigs" : "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
        ])
    }
}

jarJar.register()
build.dependsOn tasks.jarJar
tasks.named('jar') {
    archiveClassifier = 'slim'
}
tasks.named('jarJar') {
    archiveClassifier = null
}

minecraft {
    mappings channel: 'official', version: minecraft_version

    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformer = at
    }

    runs {
        configureEach {
            workingDir.convention layout.projectDirectory.dir('run')
            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
            args "--mixin.config=${mod_id}.mixins.json", "--mixin.config=${mod_id}.forge.mixins.json"
            mods {
                modClientRun {
                    source sourceSets.main
                    source project(":Common").sourceSets.main
                }
            }
        }

        register('client') {
            systemProperty 'forge.enabledGameTestNamespaces', mod_id
        }

        register('server') {
            systemProperty 'forge.enabledGameTestNamespaces', mod_id
        }

        register('data') {
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven

    maven {
        name = "Shedaniel"
        url "https://maven.shedaniel.me/"
    }

    maven { url 'https://jitpack.io' }

    flatDir {
        dirs 'libs'
    }

}


dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
    compileOnly project(":Common")
    //annotationProcessor 'net.minecraftforge:eventbus-validator:7.0-beta.7'
// Hack fix for now, force jopt-simple to be exactly 5.0.4 because Mojang ships that version, but some transitive dependencies request 6.0+
    //implementation('net.sf.jopt-simple:jopt-simple:5.0.4') { version { strictly '5.0.4' } }

    testCompileOnly(compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixinextras_version}")))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:${mixinextras_version}")) {
        jarJar.configure(it) {
            range = "[${mixinextras_version},)"
        }
    }

    //implementation fg.deobf("net.darkhax.gamestages:GameStages-Forge-1.19.2:11.0.2")

    compileOnly("me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}")

    fileTree("libs").matching {
        include "*.jar"
    }.each {
        String filename = it.getName();
        filename = filename.substring(0, filename.length() - 4);
        int lastDash = filename.lastIndexOf("-");
        filename = filename.substring(0, lastDash) + ":" + filename.substring(lastDash+1, filename.length());
        implementation "blank:${filename}"
    }


}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}